/**
 * G-NEXUS Export Service
 * 
 * Provides export functionality for workflows in multiple formats:
 * - PDF (styled document)
 * - Markdown (developer-friendly)
 * - JSON (machine-readable)
 */

import { toast } from 'sonner';

// ============================================================================
// TYPES
// ============================================================================

export interface WorkflowExportData {
    goal: string;
    blueprint?: string;
    research: Array<{
        label: string;
        content: string;
        status: string;
    }>;
    generatedCode?: Array<{
        name: string;
        path: string;
        content: string;
        language: string;
    }>;
    htmlPreview?: string;
    timestamp: Date;
    nodeCount: number;
}

export type ExportFormat = 'pdf' | 'markdown' | 'json' | 'html';

export interface ExportOptions {
    format: ExportFormat;
    includeCode?: boolean;
    includePreview?: boolean;
    theme?: 'light' | 'dark';
}

// ============================================================================
// MARKDOWN EXPORT
// ============================================================================

export function exportToMarkdown(data: WorkflowExportData): string {
    const sections: string[] = [];

    // Header
    sections.push(`# ${data.goal}\n`);
    sections.push(`**Generated**: ${data.timestamp.toLocaleString()}\n`);
    sections.push(`**Nodes**: ${data.nodeCount}\n`);
    sections.push('---\n');

    // Blueprint
    if (data.blueprint) {
        sections.push('## 🎯 Blueprint\n');
        sections.push(data.blueprint);
        sections.push('\n---\n');
    }

    // Research Results
    if (data.research.length > 0) {
        sections.push('## 🔍 Research Results\n');
        data.research.forEach((r, idx) => {
            sections.push(`### ${idx + 1}. ${r.label}\n`);
            sections.push(`**Status**: ${r.status}\n`);
            sections.push(r.content);
            sections.push('\n');
        });
        sections.push('---\n');
    }

    // Generated Code
    if (data.generatedCode && data.generatedCode.length > 0) {
        sections.push('## 💻 Generated Code\n');
        data.generatedCode.forEach(file => {
            sections.push(`### \`${file.name}\`\n`);
            sections.push(`**Path**: \`${file.path}\`\n\n`);
            sections.push(`\`\`\`${file.language}\n`);
            sections.push(file.content);
            sections.push('\n```\n\n');
        });
        sections.push('---\n');
    }

    // Footer
    sections.push('\n*Generated by G-NEXUS AI Workflow System*\n');

    return sections.join('\n');
}

// ============================================================================
// JSON EXPORT
// ============================================================================

export function exportToJSON(data: WorkflowExportData): string {
    const exportObj = {
        version: '1.0',
        generator: 'G-NEXUS',
        timestamp: data.timestamp.toISOString(),
        workflow: {
            goal: data.goal,
            blueprint: data.blueprint,
            nodeCount: data.nodeCount
        },
        research: data.research,
        generatedCode: data.generatedCode,
        htmlPreview: data.htmlPreview
    };

    return JSON.stringify(exportObj, null, 2);
}

// ============================================================================
// HTML EXPORT
// ============================================================================

export function exportToHTML(data: WorkflowExportData): string {
    const escapedGoal = escapeHtml(data.goal);
    const escapedBlueprint = data.blueprint ? escapeHtml(data.blueprint) : '';

    return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${escapedGoal} - G-NEXUS Export</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #333;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            padding: 40px 20px;
        }

        .container {
            max-width: 900px;
            margin: 0 auto;
            background: white;
            border-radius: 20px;
            box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
            overflow: hidden;
        }

        .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 40px;
            text-align: center;
        }

        .header h1 {
            font-size: 2.5em;
            margin-bottom: 10px;
        }

        .header .meta {
            opacity: 0.9;
            font-size: 0.9em;
        }

        .content {
            padding: 40px;
        }

        .section {
            margin-bottom: 40px;
        }

        .section h2 {
            color: #667eea;
            margin-bottom: 20px;
            padding-bottom: 10px;
            border-bottom: 2px solid #667eea;
        }

        .research-item {
            background: #f8f9fa;
            padding: 20px;
            border-radius: 10px;
            margin-bottom: 20px;
        }

        .research-item h3 {
            color: #764ba2;
            margin-bottom: 10px;
        }

        .research-item .status {
            display: inline-block;
            padding: 4px 12px;
            background: #4caf50;
            color: white;
            border-radius: 20px;
            font-size: 0.85em;
            margin-bottom: 10px;
        }

        .code-block {
            background: #1e1e1e;
            color: #d4d4d4;
            padding: 20px;
            border-radius: 10px;
            margin: 20px 0;
            overflow-x: auto;
        }

        .code-block .filename {
            color: #4ec9b0;
            font-weight: bold;
            margin-bottom: 10px;
        }

        .code-block pre {
            margin: 0;
            font-family: 'Consolas', 'Monaco', monospace;
            font-size: 0.9em;
        }

        .footer {
            text-align: center;
            padding: 20px;
            color: #666;
            border-top: 1px solid #e0e0e0;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>${escapedGoal}</h1>
            <div class="meta">
                Generated: ${data.timestamp.toLocaleString()} | 
                Nodes: ${data.nodeCount}
            </div>
        </div>

        <div class="content">
            ${data.blueprint ? `
            <div class="section">
                <h2>🎯 Blueprint</h2>
                <p>${escapedBlueprint.replace(/\n/g, '<br>')}</p>
            </div>
            ` : ''}

            ${data.research.length > 0 ? `
            <div class="section">
                <h2>🔍 Research Results</h2>
                ${data.research.map((r, idx) => `
                    <div class="research-item">
                        <h3>${idx + 1}. ${escapeHtml(r.label)}</h3>
                        <span class="status">${escapeHtml(r.status)}</span>
                        <p>${escapeHtml(r.content).replace(/\n/g, '<br>')}</p>
                    </div>
                `).join('')}
            </div>
            ` : ''}

            ${data.generatedCode && data.generatedCode.length > 0 ? `
            <div class="section">
                <h2>💻 Generated Code</h2>
                ${data.generatedCode.map(file => `
                    <div class="code-block">
                        <div class="filename">${escapeHtml(file.name)}</div>
                        <pre><code>${escapeHtml(file.content)}</code></pre>
                    </div>
                `).join('')}
            </div>
            ` : ''}
        </div>

        <div class="footer">
            <p>Generated by <strong>G-NEXUS</strong> AI Workflow System</p>
        </div>
    </div>
</body>
</html>`;
}

// ============================================================================
// PDF EXPORT (using jsPDF)
// ============================================================================

export async function exportToPDF(data: WorkflowExportData): Promise<Blob> {
    try {
        // Dynamic import to reduce bundle size
        const { default: jsPDF } = await import('jspdf');

        const doc = new jsPDF({
            orientation: 'portrait',
            unit: 'mm',
            format: 'a4'
        });

        let y = 20;
        const pageWidth = doc.internal.pageSize.getWidth();
        const margin = 20;
        const contentWidth = pageWidth - (margin * 2);

        // Title
        doc.setFontSize(24);
        doc.setTextColor(102, 126, 234); // Primary color
        doc.text(data.goal, margin, y);
        y += 10;

        // Metadata
        doc.setFontSize(10);
        doc.setTextColor(100, 100, 100);
        doc.text(`Generated: ${data.timestamp.toLocaleString()}`, margin, y);
        y += 5;
        doc.text(`Nodes: ${data.nodeCount}`, margin, y);
        y += 15;

        // Separator line
        doc.setDrawColor(102, 126, 234);
        doc.line(margin, y, pageWidth - margin, y);
        y += 10;

        // Blueprint
        if (data.blueprint) {
            doc.setFontSize(16);
            doc.setTextColor(0, 0, 0);
            doc.text('🎯 Blueprint', margin, y);
            y += 8;

            doc.setFontSize(10);
            doc.setTextColor(60, 60, 60);
            const blueprintLines = doc.splitTextToSize(data.blueprint, contentWidth);
            doc.text(blueprintLines, margin, y);
            y += blueprintLines.length * 5 + 10;

            // Add page if needed
            if (y > 270) {
                doc.addPage();
                y = 20;
            }
        }

        // Research Results
        if (data.research.length > 0) {
            doc.setFontSize(16);
            doc.setTextColor(0, 0, 0);
            doc.text('🔍 Research Results', margin, y);
            y += 8;

            data.research.forEach((r, idx) => {
                if (y > 250) {
                    doc.addPage();
                    y = 20;
                }

                doc.setFontSize(12);
                doc.setTextColor(118, 75, 162); // Secondary color
                doc.text(`${idx + 1}. ${r.label}`, margin, y);
                y += 6;

                doc.setFontSize(9);
                doc.setTextColor(60, 60, 60);
                const contentLines = doc.splitTextToSize(r.content.substring(0, 500) + '...', contentWidth);
                doc.text(contentLines, margin, y);
                y += contentLines.length * 4 + 8;
            });
        }

        // Generated Code
        if (data.generatedCode && data.generatedCode.length > 0) {
            if (y > 250) {
                doc.addPage();
                y = 20;
            }

            doc.setFontSize(16);
            doc.setTextColor(0, 0, 0);
            doc.text('💻 Generated Code', margin, y);
            y += 8;

            data.generatedCode.forEach(file => {
                if (y > 240) {
                    doc.addPage();
                    y = 20;
                }

                doc.setFontSize(11);
                doc.setTextColor(78, 201, 176); // Code color
                doc.text(file.name, margin, y);
                y += 6;

                doc.setFontSize(8);
                doc.setFont('courier');
                doc.setTextColor(40, 40, 40);
                const codeLines = doc.splitTextToSize(file.content.substring(0, 1000) + '...', contentWidth);
                doc.text(codeLines, margin, y);
                y += codeLines.length * 3.5 + 10;
                doc.setFont('helvetica');
            });
        }

        // Footer on last page
        const pageCount = doc.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.setTextColor(150, 150, 150);
            doc.text(
                `Generated by G-NEXUS | Page ${i} of ${pageCount}`,
                pageWidth / 2,
                doc.internal.pageSize.getHeight() - 10,
                { align: 'center' }
            );
        }

        return doc.output('blob');
    } catch (error) {
        console.error('[ExportService] PDF generation failed:', error);
        throw new Error('Failed to generate PDF. Make sure jsPDF is installed.');
    }
}

// ============================================================================
// DOWNLOAD HELPERS
// ============================================================================

export function downloadFile(content: string | Blob, filename: string, mimeType: string) {
    const blob = typeof content === 'string'
        ? new Blob([content], { type: mimeType })
        : content;

    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
}

export async function exportWorkflow(data: WorkflowExportData, options: ExportOptions): Promise<void> {
    try {
        const timestamp = data.timestamp.toISOString().split('T')[0];
        const baseName = data.goal.replace(/[^a-z0-9]/gi, '_').toLowerCase().substring(0, 30);

        switch (options.format) {
            case 'markdown': {
                const md = exportToMarkdown(data);
                downloadFile(md, `${baseName}_${timestamp}.md`, 'text/markdown');
                toast.success('📄 Exported to Markdown!');
                break;
            }

            case 'json': {
                const json = exportToJSON(data);
                downloadFile(json, `${baseName}_${timestamp}.json`, 'application/json');
                toast.success('📊 Exported to JSON!');
                break;
            }

            case 'html': {
                const html = exportToHTML(data);
                downloadFile(html, `${baseName}_${timestamp}.html`, 'text/html');
                toast.success('🌐 Exported to HTML!');
                break;
            }

            case 'pdf': {
                toast.info('📄 Generating PDF...');
                const pdfBlob = await exportToPDF(data);
                downloadFile(pdfBlob, `${baseName}_${timestamp}.pdf`, 'application/pdf');
                toast.success('📄 Exported to PDF!');
                break;
            }

            default:
                throw new Error(`Unknown export format: ${options.format}`);
        }
    } catch (error: any) {
        console.error('[ExportService] Export failed:', error);
        toast.error(`Export failed: ${error.message}`);
        throw error;
    }
}

// ============================================================================
// UTILITIES
// ============================================================================

function escapeHtml(text: string): string {
    const map: Record<string, string> = {
        '&': '&amp;',
        '<': '&lt;',
        '>': '&gt;',
        '"': '&quot;',
        "'": '&#039;'
    };
    return text.replace(/[&<>"']/g, m => map[m]);
}
