/**
 * G-NEXUS NEURAL CORE
 * AI-Powered Intelligence Engine for "FutureOS"
 * 
 * Generates structured content using real AI with self-correction.
 */

import { generateText } from './ai';

// =============================================================================
// TYPES
// =============================================================================

export type NeuralIntent = 'comparison' | 'timeline' | 'analysis' | 'growth' | 'ecosystem';

export interface NeuralMetric {
    label: string;
    value: string;
    trend: 'up' | 'down' | 'neutral';
    delta: string;
}

export interface NeuralChartData {
    labels: string[];
    datasets: {
        label: string;
        data: number[];
        color?: string;
    }[];
}

export interface NeuralContent {
    title: string;
    subtitle: string;
    intent: NeuralIntent;
    brief: string;
    sections: {
        title: string;
        content: string[];
        type: 'text' | 'list' | 'cards' | 'steps';
    }[];
    metrics: NeuralMetric[];
    chart?: {
        title: string;
        type: 'bar' | 'line' | 'radar';
        data: NeuralChartData;
    };
    comparison?: {
        items: string[];
        features: { name: string; values: boolean[] | string[] }[];
    };
}

// =============================================================================
// CORE LOGIC
// =============================================================================

/**
 * Analyzes the user prompt to determine the best layout intent
 */
export function analyzeIntent(prompt: string): NeuralIntent {
    const p = prompt.toLowerCase();

    if (p.includes('vs') || p.includes('compare') || p.includes('difference') || p.includes('alternatives')) {
        return 'comparison';
    }
    if (p.includes('history') || p.includes('roadmap') || p.includes('evolution') || p.includes('timeline')) {
        return 'timeline';
    }
    if (p.includes('growth') || p.includes('scale') || p.includes('market size') || p.includes('revenue')) {
        return 'growth';
    }
    if (p.includes('ecosystem') || p.includes('stack') || p.includes('architecture')) {
        return 'ecosystem';
    }

    return 'analysis';
}

/**
 * Validates if the content matches the NeuralContent schema
 */
function validateNeuralContent(content: any): content is NeuralContent {
    return (
        typeof content === 'object' &&
        typeof content.title === 'string' &&
        typeof content.subtitle === 'string' &&
        typeof content.intent === 'string' &&
        typeof content.brief === 'string' &&
        Array.isArray(content.sections) &&
        Array.isArray(content.metrics)
    );
}

/**
 * Generates fallback content (used when AI fails or as last resort)
 */
function generateFallbackContent(prompt: string): NeuralContent {
    const p = prompt.toLowerCase();
    const intent = analyzeIntent(prompt);

    // Default structure
    const content: NeuralContent = {
        title: `Deep Analysis: ${prompt}`,
        subtitle: 'Generated by G-Nexus Neural Core',
        intent,
        brief: 'Comprehensive breakdown of key trends, metrics, and strategic recommendations.',
        sections: [],
        metrics: [
            { label: 'Relevance Score', value: '98%', trend: 'up', delta: '+2.4%' },
            { label: 'Market Velocity', value: 'High', trend: 'up', delta: 'Active' },
            { label: 'Data Points', value: '1.2M', trend: 'neutral', delta: 'Stable' },
            { label: 'Confidence', value: 'High', trend: 'up', delta: '99.9%' }
        ]
    };

    // 1. AI / FREE TOOLS TOPIC
    if (p.includes('ai') || p.includes('gpt') || p.includes('llm')) {
        content.title = p.includes('free') ? 'Zero-Cost AI Ecosystem Report' : 'Advanced AI Landscape Analysis';
        content.subtitle = 'Exploring the frontier of open-source and democratized intelligence.';

        content.sections = [
            {
                title: 'Market Shift',
                type: 'text',
                content: [
                    'The democratization of AI is accelerating. Proprietary models are being challenged by high-performance open-source alternatives.',
                    'Edge computing and local inference are becoming viable for consumer hardware.'
                ]
            },
            {
                title: 'Top Recommended Tools',
                type: 'cards',
                content: [
                    'Ollama: Local inference runner for Llama 3 & Mistral',
                    'HuggingFace: The "GitHub of AI" - massive model repository',
                    'Vercel AI SDK: Best-in-class developer experience for integration'
                ]
            }
        ];

        content.metrics = [
            { label: 'Cost Savings', value: '100%', trend: 'up', delta: 'Vs Proprietary' },
            { label: 'Model Count', value: '450k+', trend: 'up', delta: 'HuggingFace' },
            { label: 'Inference Speed', value: '45ms', trend: 'up', delta: 'Latency' },
            { label: 'Adoption Rate', value: '85%', trend: 'up', delta: 'YoY Growth' }
        ];

        content.chart = {
            title: 'Open Source Model Performance vs Cost',
            type: 'line',
            data: {
                labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
                datasets: [
                    { label: 'Performance (MMLU)', data: [65, 68, 72, 75, 79, 82], color: '#a855f7' },
                    { label: 'Cost ($/1M Tok)', data: [5, 4, 3, 2, 1, 0.5], color: '#22c55e' }
                ]
            }
        };

        if (intent === 'comparison') {
            content.comparison = {
                items: ['OpenAI', 'Anthropic', 'Llama (Open)'],
                features: [
                    { name: 'Cost', values: ['High', 'Medium', 'Free'] },
                    { name: 'Privacy', values: ['Cloud', 'Cloud', 'Local'] },
                    { name: 'Customizability', values: ['Low', 'Medium', 'High'] }
                ]
            };
        }
    }

    // 2. CRYPTO / FINANCE TOPIC
    else if (p.includes('crypto') || p.includes('finance') || p.includes('bitcoin')) {
        content.title = 'Digital Asset Market Intelligence';
        content.subtitle = 'Real-time analysis of decentralized finance protocols and trends.';

        content.sections = [
            {
                title: 'Market Sentiment',
                type: 'text',
                content: [
                    'Institutional adoption is driving the current cycle. ETFs and regulated products are bridging the gap.',
                    'DeFi liquidity is returning to 2021 levels with improved security standards.'
                ]
            },
            {
                title: 'Key Protocols',
                type: 'list',
                content: [
                    'Ethereum (L1): The settlement layer for the global web',
                    'Solana (L1): High-speed execution environment',
                    'Uniswap (DEX): Market leading decentralized exchange'
                ]
            }
        ];

        content.metrics = [
            { label: 'TVL', value: '$85B', trend: 'up', delta: '+12% 24h' },
            { label: 'Active Wallets', value: '2.4M', trend: 'up', delta: 'Daily' },
            { label: 'Gas Fee', value: '12 gwei', trend: 'down', delta: 'Low' },
            { label: 'Dominance', value: '52%', trend: 'neutral', delta: 'BTC' }
        ];

        content.chart = {
            title: 'Layer 2 Transaction Volume',
            type: 'bar',
            data: {
                labels: ['Optimism', 'Arbitrum', 'Base', 'Polygon', 'zkSync'],
                datasets: [
                    { label: 'Daily TX (Millions)', data: [2.1, 3.5, 4.2, 1.8, 1.2], color: '#10b981' }
                ]
            }
        };
    }

    // 3. HEALTH / MEDICAL TOPIC
    else if (p.includes('health') || p.includes('medical')) {
        content.title = 'Healthcare Innovation Report';
        content.metrics = [
            { label: 'Patient Outcomes', value: '+34%', trend: 'up', delta: 'With AI' },
            { label: 'Cost Reduction', value: '22%', trend: 'down', delta: 'Admin' }
        ];
        // ... (similar expansion)
    }

    return content;
}

/**
 * Generates high-fidelity structured data using AI with self-correction
 */
export async function generateNeuralContent(prompt: string): Promise<NeuralContent> {
    const p = prompt.toLowerCase();
    const intent = analyzeIntent(prompt);

    // Construct a strict system prompt for JSON generation
    const systemPrompt = `You are a Neural Content Generator. Generate a valid JSON object matching this TypeScript interface:

interface NeuralContent {
    title: string;
    subtitle: string;
    intent: '${intent}';
    brief: string;
    sections: { title: string; content: string[]; type: 'text' | 'list' | 'cards' | 'steps' }[];
    metrics: { label: string; value: string; trend: 'up' | 'down' | 'neutral'; delta: string }[];
    chart?: { title: string; type: 'bar' | 'line' | 'radar'; data: { labels: string[]; datasets: { label: string; data: number[]; color?: string }[] } };
    comparison?: { items: string[]; features: { name: string; values: (boolean | string)[] }[] };
}

CRITICAL: Return ONLY valid JSON. No markdown, no explanation, just the JSON object.`;

    const userPrompt = `Generate comprehensive neural content for: "${prompt}"

Guidelines:
- Make the title compelling and specific to the topic
- Include 2-4 detailed sections with rich content
- Provide 4 realistic metrics with trends
- If the topic involves comparison, add the comparison object
- If data visualization makes sense, include a chart

Topic: ${prompt}`;

    // Attempt AI generation with retry logic
    const maxRetries = 3;
    let lastError = '';

    for (let attempt = 0; attempt < maxRetries; attempt++) {
        try {
            console.log(`[NeuralCore] AI Generation attempt ${attempt + 1}/${maxRetries}`);

            const response = await generateText('analyst', userPrompt, {
                temperature: 0.7,
                max_new_tokens: 3000
            });

            if (!response.success || !response.data) {
                lastError = response.error || 'Empty response';
                console.warn(`[NeuralCore] Attempt ${attempt + 1} failed:`, lastError);
                continue;
            }

            // Clean up response (remove markdown code blocks if present)
            let jsonText = response.data.trim();
            if (jsonText.startsWith('```')) {
                jsonText = jsonText.replace(/^```(?:json)?\n?/i, '').replace(/\n?```$/, '');
            }

            // Parse JSON
            const parsed = JSON.parse(jsonText);

            // Validate schema
            if (validateNeuralContent(parsed)) {
                console.log('[NeuralCore] ✓ AI generation successful');
                return parsed;
            } else {
                lastError = 'Schema validation failed';
                console.warn('[NeuralCore] Invalid schema, attempting self-correction...');

                // Self-correction attempt
                if (attempt < maxRetries - 1) {
                    const correctionPrompt = `The following JSON is invalid according to the NeuralContent schema. Fix it and return ONLY the corrected JSON:

${jsonText}

Required schema: ${systemPrompt}`;

                    const corrected = await generateText('analyst', correctionPrompt);
                    if (corrected.success && corrected.data) {
                        const fixedJson = corrected.data.trim().replace(/^```(?:json)?\n?/i, '').replace(/\n?```$/, '');
                        const fixedParsed = JSON.parse(fixedJson);
                        if (validateNeuralContent(fixedParsed)) {
                            console.log('[NeuralCore] ✓ Self-correction successful');
                            return fixedParsed;
                        }
                    }
                }
            }
        } catch (error: any) {
            lastError = error.message;
            console.warn(`[NeuralCore] Attempt ${attempt + 1} error:`, error.message);
        }
    }

    // All attempts failed, use intelligent fallback
    console.warn('[NeuralCore] All AI attempts failed, using fallback generator');
    console.warn('[NeuralCore] Last error:', lastError);

    return generateFallbackContent(prompt);
}
